### ISSUE TITLE
a bug on unicorn loading animation

### ISSUE THREAD

**Issue by chunza2542** [Th1nkK1D/k1d.me#1]
![screen shot 2017-12-22 at 4 28 08 pm](https://user-images.githubusercontent.com/8079099/34292898-3796d538-e735-11e7-80fd-4f074d983b7b.png)

set `scroll` to `hidden` on `body` tag.

**Comment by Th1nkK1D** [comment]
Fixed using `overflow: hidden;` in case of scrolling in the future 
Thanks for reporting krub :)
